### ISSUE TITLE
It's better to change DPI to 1.5

### ISSUE THREAD

**Issue by gbowsky** [sailfish-lavender/builds#1]
Because everything is really too big (also 1.5x dpi scaling hides clock which already overlapped by notch)

**Comment by Danct12** [comment]
Good suggestion, I'll play around with that value in next preview build.

**Comment by ScardracS-zz** [comment]
We have to find out a method to move clock right or left as in android because it stay right under the notch

**Comment by ScardracS** [comment]
We have to find out a method to move clock right or left as in android because it stay right under the notch

**Comment by Danct12** [comment]
@ScardracS Sorry for the deletion ^ but that's because you posted the same comment twice

As for the clock, I believe there's no way we can tamper with lipstick's source code, otherwise it would've been added long ago.

So the best idea here is to modify libhybris's hwc2 to omit the notch, which means where the notch is located is just a black texture.

**Comment by Danct12** [comment]
I think 1.75 looks good, it's not too small, and it doesn't look too big either.

**Comment by Danct12** [comment]
Now a part of the new [20200429 Preview](https://github.com/sailfish-lavender/builds/releases/tag/20200429)

https://github.com/sailfish-lavender/droid-config-lavender/commit/924bd9ec6cf784c1374d2be33212a8f214338c24
